---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration for wordpress
  become: yes
  become_user: root
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf

- name: Restart nginx
  service: name=nginx state=restarted enabled=yes