---
- name: Download WordPress
  become: yes
  become_user: root
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Extract archive
  become: yes
  become_user: root
  command: chdir=/srv/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/srv/wordpress

- name: Add group "wordpress"
  become: yes
  become_user: root
  group: name=wordpress

- name: Add user "wordpress"
  become: yes
  become_user: root
  user: name=wordpress group=wordpress home=/srv/wordpress/

- name: Copy WordPress config file
  become: yes
  become_user: root
  template: src=wp-config.php dest=/srv/wordpress/

- name: Change ownership of WordPress installation
  become: yes
  become_user: root
  file: path=/srv/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes

- name: Start php-fpm Service
  become: yes
  become_user: root
  service: name=php5-fpm state=started enabled=yes