---
- name: Install php-fpm and deps
  become: yes
  become_user: root
  apt: name={{ item }} state=present  update_cache=yes
  with_items:
    - php5
    - php5-fpm
    - php5-mysql

- name: Disable default pool
  become: yes
  become_user: root
  command: mv /etc/php5/fpm/pool.d/www.conf /etc/php5/fpm/pool.d/www.disabled  creates=/etc/php5/fpm/pool.d/www.disabled

- name: Copy php-fpm configuration
  become: yes
  become_user: root
  template: src=wordpress.conf dest=/etc/php5/fpm/conf.d/

- name: restart php-fpm
  become: yes
  become_user: root
  service: name=php5-fpm state=restarted